// ─── RAG memory persistence (cards / trace / context / promote) ───────────────
//
// Pure-TS reimplementation of the card/trace/context/promote feature set from
// the reference `rag` Claude plugin. There is no Rust counterpart — this file
// is the single source of truth for the corpus stored under
// `<project>/.opencode/memory/`.

import {
  mkdirSync,
  readFileSync,
  writeFileSync,
  appendFileSync,
  existsSync,
  readdirSync,
  statSync,
  rmSync,
} from "fs";
import { join, dirname, sep, isAbsolute } from "path";

// ─── Root resolution ────────────────────────────────────────────────────────────

export function memoryRoot(): string {
  const dir = join(process.cwd(), ".opencode", "memory");
  mkdirSync(dir, { recursive: true });
  return dir;
}

// ─── Card id sanitization ───────────────────────────────────────────────────────

// Path separators + characters illegal on Windows/exFAT + control chars.
const UNSAFE_CARD_CHARS = /[<>:"/\\|?*\x00-\x1f]/g;

/**
 * Reduce an arbitrary id to one safe path component with a canonical CARD-
 * prefix. Exact parity with the reference plugin's `normalize_card_name`:
 * strip '#', neutralize path separators / FS-hostile characters, drop
 * pure-dot segments ('.', '..', '...'), collapse whitespace/hyphens, and
 * canonicalize the CARD- prefix (case-insensitive detection, never doubled).
 */
export function sanitizeCardId(raw: string): string {
  const withoutHash = raw.split("#").join("");
  const cleaned = withoutHash.replace(UNSAFE_CARD_CHARS, " ");
  const parts = cleaned
    .split(/\s+/)
    .filter((p) => p.length > 0)
    .filter((p) => p.replace(/^\.+|\.+$/g, "").length > 0);

  let name = parts
    .join("-")
    .replace(/-{2,}/g, "-")
    .replace(/^[-.]+|[-.]+$/g, "");

  if (!name) {
    throw new Error(`card id is empty after sanitization: ${JSON.stringify(raw)}`);
  }

  name = name.toUpperCase().startsWith("CARD-") ? "CARD-" + name.slice(5) : "CARD-" + name;

  if (name.includes("/") || name.includes("\\") || name.includes(sep)) {
    throw new Error(`invalid card id after sanitization: ${JSON.stringify(name)}`);
  }
  return name;
}

// ─── Date helpers ────────────────────────────────────────────────────────────

function pad2(n: number): string {
  return String(n).padStart(2, "0");
}

function todayIso(): string {
  const d = new Date();
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}

function nowMinuteIso(): string {
  const d = new Date();
  return `${todayIso()} ${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
}

// ─── Corpus scaffolding ──────────────────────────────────────────────────────

const SYSTEM_SUBDIRS = ["architecture", "schemas", "services", "known-behaviors"] as const;
const ISSUE_SUBDIRS = ["backlog", "active", "done", "archive"] as const;

export const CORPUS_GITIGNORE = `# .opencode/memory commit boundary — what stays local vs. what is committed.
# Generated by scaffoldCorpus(). Edit to taste; the defaults enforce the documented boundary.

# --- Local working state — never committed ---
issues/backlog/
issues/active/
issues/done/

# --- Trace logs are local working state, even for archived cards ---
**/trace.md

# Committed surface = system/** + issues/archive/** (context.md, benchmarks.md, artifacts/)
`;

export const RAG_META = {
  format_gen: { doc: 3, card: 1 },
  plugin: "memory",
};

const ROOT_README = `# RAG Memory System

A two-layer retrieval-augmented memory system for investigation work.

## Layers

- **System Knowledge** (\`system/\`) — Long-term, versioned knowledge about the codebase, schemas, services, and confirmed behaviors. The durable layer. **Committed to Git.**
- **Issue Memory** (\`issues/\`) — Investigation cards across their lifecycle: planned (\`backlog/\`), active, finished-locally (\`done/\`), and the durable committed record (\`archive/\`). Mostly local working state.

## Directory Layout

\`\`\`
.opencode/memory/
├── README.md              ← You are here
├── BENCHMARKS.md          ← What constitutes a benchmark moment
├── .gitignore             ← Commit boundary: local working state vs. committed record
├── system/
│   ├── README.md
│   ├── architecture/      ← Repo maps, integration topology, deployment layout
│   ├── schemas/           ← DDL summaries, table relationships, schema quirks
│   ├── services/          ← Per-service behavior, config edge cases, controller quirks
│   └── known-behaviors/   ← Promoted findings from issues — confirmed system behaviors
└── issues/
    ├── README.md
    ├── backlog/           ← Planned, not yet active (local, gitignored)
    ├── active/            ← Current investigation cards (local, gitignored)
    ├── done/              ← Finished locally, kept per-dev (local, gitignored)
    └── archive/           ← Durable, committed shared record (trace.md excluded)
\`\`\`

## Navigation

- To understand what goes in \`system/\`, read \`system/README.md\`
- To understand the card lifecycle, read \`issues/README.md\`
- To understand benchmark promotion, read \`BENCHMARKS.md\`

## Promotion Rules

When analysis on an active issue yields a finding that teaches something **durable** about the system
— not just how to fix this card, but how the system behaves in a category of situations — promote it
from the issue card into \`system/known-behaviors/\` (or another appropriate \`system/\` subfolder) via
\`promoteFinding()\`. When closing a card, sweep its \`trace.md\` for benchmark-worthy findings that were
never tagged, so none are stranded.

See \`BENCHMARKS.md\` for the full checklist.

## Curation Policy

| Layer | Location | Retention | Git-versioned? |
|---|---|---|---|
| System knowledge | \`system/\` | Permanent, updated | **Yes** |
| Backlog (planned) | \`issues/backlog/\` | Until activated or dropped | **No — local** |
| Active issues | \`issues/active/\` | Duration of card | **No — local** |
| Done (finished locally) | \`issues/done/\` | Per-dev preference | **No — local** |
| Archived issues | \`issues/archive/\` | Indefinite, durable | **Yes — except \`trace.md\`** |
| Trace logs | \`**/trace.md\` | Local working state | **Never committed** |
| Promoted benchmarks | \`system/known-behaviors/\` | Permanent | **Yes** |
`;

const ISSUES_README = `# Issue Memory

This directory holds investigation cards across their lifecycle: planned (backlog), under
investigation (active), finished-locally (done), and the durable committed record (archive).

## Card Lifecycle

1. **Plan (optional)** — Park a not-yet-started idea as a card in \`backlog/\` (local, per-dev) via
   \`createCard({ cardId, backlog: true })\`.
2. **Create / Activate** — Start work by creating a card in \`active/\` with \`createCard()\`
   (or move one from \`backlog/\` to \`active/\`).
3. **Investigate** — Use \`appendTrace()\` to log findings, rule-outs, hypotheses, and next steps.
4. **Promote** — When a finding is durable, use \`promoteFinding()\` to write it to \`system/\`.
5. **Close — pick a terminal state:**
   - **Done** → move the card to \`done/\`. Local, dev-managed; **not committed**.
   - **Archive** → move the card to \`archive/\`. This is the **durable, committed shared record**.

## Directory Layout

| Subfolder | Contents | Git |
|---|---|---|
| \`backlog/\` | Planned, not yet active | Local (gitignored) |
| \`active/\` | Cards currently under investigation | Local (gitignored) |
| \`done/\` | Finished locally, kept per-dev | Local (gitignored) |
| \`archive/\` | Durable shared record | **Committed** (except \`trace.md\`) |

## Card Structure

Each card lives in \`CARD-XXXXX/\` and contains:

- \`context.md\` — Issue ID, source, symptom, repos, related issues  *(committed in archive/)*
- \`trace.md\` — Running analysis log (append-only)  *(always local — never committed)*
- \`benchmarks.md\` — Benchmark moments found during this investigation  *(committed in archive/)*
- \`artifacts/\` — Code snippets, DDL excerpts, log samples, schema diffs  *(committed in archive/)*

Backlog cards start with \`context.md\` only; \`trace.md\` / \`benchmarks.md\` / \`artifacts/\` appear when
the card is activated.

## Close Checklist (before moving out of \`active/\`)

- [ ] \`trace.md\` swept for un-tagged benchmark-worthy findings
- [ ] All benchmark moments reviewed (promoted or rejected) — no \`pending\` left in \`benchmarks.md\`
- [ ] Related issues in other active cards updated if needed
- [ ] Destination chosen: \`done/\` (local) or \`archive/\` (committed)
`;

const SYSTEM_README = `# System Knowledge

This directory contains long-term, versioned knowledge about the system. Everything here should be **durable** — it describes how the system works, not how a specific issue was investigated.

## What Belongs Here

| Subfolder | Contents |
|---|---|
| \`architecture/\` | Repo maps, integration topology, deployment layout |
| \`schemas/\` | DDL summaries, table relationships, known schema quirks |
| \`services/\` | Per-service behavior docs, config edge cases, controller quirks |
| \`known-behaviors/\` | Promoted findings from issue investigations — confirmed system gotchas |

## Format Standards

Each file in \`system/\` opens with a YAML **frontmatter** header (file-level, machine-parseable
metadata) followed by the body. Provenance is **hybrid**: the header aggregates it for the whole
file, while each finding keeps its own \`**Source**\` line — a single file often gathers findings from
several cards.

\`\`\`markdown
---
title: [Topic Title — mirrors the H1]
domain: [subfolder under system/ — e.g. known-behaviors, or nested area/subarea]
source_cards: [CARD-XXXXX]
created: YYYY-MM-DD
updated: YYYY-MM-DD
status: active
format_gen: 3
tags: []
---

# [Topic Title]

## [Section per finding or topic]
**Source**: CARD-XXXXX | YYYY-MM-DD  (if promoted from an issue)
**Finding**: What was learned
**Impact**: What this affects going forward
\`\`\`

## Update Policy

- **Add** when a benchmark moment is promoted from an issue card (via \`promoteFinding()\`)
- **Update** when new investigation refines or corrects existing knowledge
- **Never delete** without moving to an archive or leaving a deprecation note
- **Always commit** changes to Git after updates
`;

const BENCHMARKS_POLICY = `# Benchmark Moments — Definition & Policy

## What Is a Benchmark Moment?

A confirmed finding from an issue investigation that reveals something durable and reusable about the system. It answers a question that would recur across future issues.

Examples:
- A hard-coded constant that causes log truncation under specific conditions
- A schema relationship that isn't documented but affects query behavior
- A service interaction pattern that fails silently in edge cases

## Promotion Checklist

- [ ] Finding has been confirmed (not just hypothesized)
- [ ] It applies beyond this specific card
- [ ] A target file in \`system/\` has been identified
- [ ] The finding has been written in \`system/\` format (context-focused, not issue-specific)
- [ ] \`benchmarks.md\` in the card has been updated to \`promoted\`
- [ ] \`trace.md\` swept for un-tagged benchmark-worthy findings (none stranded)

## Tags

Use these status values in each card's \`benchmarks.md\`:

- \`pending\` → Confirmed finding, not yet promoted to \`system/\`
- \`promoted\` → Written to \`system/\`, includes target path and date
- \`rejected\` → Reviewed, determined to be too issue-specific to promote

## Format in Card benchmarks.md

Each entry in a card's \`benchmarks.md\` should follow this format:

\`\`\`
---
date: YYYY-MM-DD
session: opencode / manual
finding: Short description of what was learned
target: system/known-behaviors/example-filename.md
status: pending | promoted | rejected
---
\`\`\`

## Promotion Lifecycle

1. Finding made during issue analysis
2. Determine: is this specific to this issue only? If yes, log in \`trace.md\` only.
3. If it reveals something about system behavior, schema design, or service interaction → tag in \`benchmarks.md\` as \`pending\`
4. Identify target: \`system/known-behaviors/\`, \`system/services/\`, \`system/schemas/\`, or \`system/architecture/\`
5. Write or append to the target \`system/\` file (via \`promoteFinding()\`)
6. Mark \`benchmarks.md\` entry as \`promoted\` with file path and date
7. Commit \`system/\` to Git

> **Sweep at close.** Before filing a card under \`done/\` or \`archive/\`, re-read its \`trace.md\` and run
> steps 3–6 on any benchmark-worthy finding that was never tagged. Findings logged only in the trace
> must not be lost. The sweep only reads the trace.
`;

function writeIfMissing(path: string, content: string): void {
  if (!existsSync(path)) {
    writeFileSync(path, content, "utf8");
  }
}

/**
 * Idempotent auto-scaffold: creates the full `.opencode/memory/` directory
 * tree, the corpus `.gitignore` commit boundary, `.rag-meta.json`, and
 * README/BENCHMARKS boilerplate. Never overwrites existing files. Called
 * automatically by `createCard`.
 */
export function scaffoldCorpus(root: string = memoryRoot()): void {
  mkdirSync(root, { recursive: true });
  for (const sub of SYSTEM_SUBDIRS) {
    mkdirSync(join(root, "system", sub), { recursive: true });
  }
  for (const sub of ISSUE_SUBDIRS) {
    mkdirSync(join(root, "issues", sub), { recursive: true });
  }

  writeIfMissing(join(root, ".gitignore"), CORPUS_GITIGNORE);
  writeIfMissing(join(root, ".rag-meta.json"), JSON.stringify(RAG_META, null, 2) + "\n");
  writeIfMissing(join(root, "README.md"), ROOT_README);
  writeIfMissing(join(root, "BENCHMARKS.md"), BENCHMARKS_POLICY);
  writeIfMissing(join(root, "system", "README.md"), SYSTEM_README);
  writeIfMissing(join(root, "issues", "README.md"), ISSUES_README);
}

// ─── Card templates ──────────────────────────────────────────────────────────

type CardTemplateMapping = {
  CARD_ID: string;
  DATE: string;
  SOURCE: string;
  SYMPTOM: string;
};

function substitute(text: string, mapping: CardTemplateMapping): string {
  return text
    .replace(/\{\{CARD_ID\}\}/g, mapping.CARD_ID)
    .replace(/\{\{DATE\}\}/g, mapping.DATE)
    .replace(/\{\{SOURCE\}\}/g, mapping.SOURCE)
    .replace(/\{\{SYMPTOM\}\}/g, mapping.SYMPTOM);
}

const CONTEXT_TEMPLATE = `---
card_id: {{CARD_ID}}
title: ""
opened: {{DATE}}
closed:
format_gen: 1
tags: []
---

# {{CARD_ID}}

## Issue Summary

- **Card ID**: {{CARD_ID}}
- **Source**: {{SOURCE}}
- **Date Opened**: {{DATE}}
- **Symptom**: {{SYMPTOM}}

## Reproduction Steps

<!-- Describe how to reproduce the issue -->

## Relevant Repos and File Ranges

<!-- List repos, branches, and specific files/line ranges relevant to this issue -->

## Relevant Schema Tables

<!-- List database tables, views, or stored procedures involved -->

## Related Prior Issues

<!-- Link to any previous cards or tickets that are related -->

## AI Session Log

<!-- Summary of AI-assisted analysis sessions on this card -->
| Date | Session | Summary |
|---|---|---|
| {{DATE}} | — | Card created |
`;

/**
 * Canonical trace.md header — shared by card creation (`createCard`) and the
 * bootstrap-on-demand path in `appendTrace`, so there is exactly one header
 * shape in this module (the reference plugin has two slightly different
 * variants; here they are unified).
 */
function traceHeader(cardId: string): string {
  return (
    `# Investigation Trace — ${cardId}\n\n` +
    "This file is an **append-only** log of the investigation. Each entry records a finding, ruled-out hypothesis, new hypothesis, or next step. Never overwrite or truncate existing entries.\n\n" +
    "Write with **asymmetric economy**: cut framing prose, keep evidence (file paths, numbers, commands, errors) verbatim. Append new entries directly — don't read the whole file back in first.\n"
  );
}

function traceTemplate(mapping: CardTemplateMapping): string {
  return (
    traceHeader(mapping.CARD_ID) +
    `\n---\ndate: ${mapping.DATE} 00:00\nsession: manual\ntype: next-step\n---\n` +
    "Card created. Begin investigation by filling out context.md and identifying first analysis targets.\n"
  );
}

function benchmarksTemplate(mapping: CardTemplateMapping): string {
  return `# Benchmark Moments — ${mapping.CARD_ID}

This file tracks findings from this investigation that may qualify as **benchmark moments** — durable, reusable insights about the system that should be promoted to \`system/\`.

See \`.opencode/memory/BENCHMARKS.md\` for the full definition and promotion checklist.

<!-- Add entries below as findings are confirmed. Use this format:

---
date: YYYY-MM-DD
session: opencode / manual
finding: Short description of what was learned
target: system/known-behaviors/example.md
status: pending | promoted | rejected
---

-->
`;
}

const ACTIVE_CARD_FILES = ["context.md", "trace.md", "benchmarks.md"] as const;
const BACKLOG_CARD_FILES = ["context.md"] as const;

function renderCardFile(fname: string, mapping: CardTemplateMapping): string {
  switch (fname) {
    case "context.md":
      return substitute(CONTEXT_TEMPLATE, mapping);
    case "trace.md":
      return traceTemplate(mapping);
    case "benchmarks.md":
      return benchmarksTemplate(mapping);
    default:
      throw new Error(`unknown card template: ${fname}`);
  }
}

// ─── Card lifecycle ──────────────────────────────────────────────────────────

export type CardState = "backlog" | "active" | "done" | "archive";
export type CardSource = "ado" | "qa" | "prod" | "other";

const LIFECYCLE_STATES: readonly CardState[] = ["backlog", "active", "done", "archive"];

export interface FoundCard {
  state: CardState;
  dir: string;
}

/** Locate a card across backlog/active/done/archive. Returns null if absent. */
export function findCard(cardId: string, root: string = memoryRoot()): FoundCard | null {
  const normalized = sanitizeCardId(cardId);
  for (const state of LIFECYCLE_STATES) {
    const dir = join(root, "issues", state, normalized);
    if (existsSync(dir)) {
      return { state, dir };
    }
  }
  return null;
}

/**
 * List the card IDs currently under `issues/active/` (directory names only —
 * stray files are ignored). Used by callers that need to know how many
 * investigations are in flight without loading each card's content, e.g. the
 * harness plugin's best-effort auto-trace-on-failure hook only wants to act
 * when there is exactly one unambiguous active card to attribute a task
 * failure to. Returns an empty array if `issues/active/` doesn't exist yet
 * (corpus never scaffolded, or scaffolded but no card ever activated).
 */
export function listActiveCards(root: string = memoryRoot()): string[] {
  const activeDir = join(root, "issues", "active");
  if (!existsSync(activeDir)) {
    return [];
  }
  return readdirSync(activeDir).filter((name) => statSync(join(activeDir, name)).isDirectory());
}

export interface CreateCardOptions {
  cardId: string;
  symptom?: string;
  source?: CardSource;
  backlog?: boolean;
  date?: string;
}

/**
 * Scaffold a new investigation card. Active cards (default) get
 * context.md + trace.md + benchmarks.md + artifacts/.gitkeep. Backlog cards
 * (`backlog: true`) get context.md only. Refuses if the card already exists
 * in any lifecycle directory. Atomic: all file contents are rendered before
 * any directory is created; a partially-written card is rolled back on
 * failure. Returns the list of files created (relative to the card dir).
 */
export function createCard(opts: CreateCardOptions, root: string = memoryRoot()): string[] {
  scaffoldCorpus(root);

  const cardId = sanitizeCardId(opts.cardId);
  const backlog = opts.backlog ?? false;
  const source = opts.source ?? "other";
  const date = opts.date ?? todayIso();
  const symptom = opts.symptom ?? "";

  if (!backlog && !symptom.trim()) {
    throw new Error("createCard: symptom is required for active cards (omit only with backlog: true)");
  }

  const existing = findCard(cardId, root);
  if (existing) {
    throw new Error(`createCard: card already exists: ${existing.dir} (refusing to overwrite)`);
  }

  const state: CardState = backlog ? "backlog" : "active";
  const cardDir = join(root, "issues", state, cardId);
  const mapping: CardTemplateMapping = { CARD_ID: cardId, DATE: date, SOURCE: source, SYMPTOM: symptom };
  const files: readonly string[] = backlog ? BACKLOG_CARD_FILES : ACTIVE_CARD_FILES;

  // Render everything before touching the filesystem so a template problem
  // fails before any directory is created.
  const rendered = new Map<string, string>();
  for (const fname of files) {
    rendered.set(fname, renderCardFile(fname, mapping));
  }

  const written: string[] = [];
  try {
    mkdirSync(cardDir, { recursive: true });
    for (const fname of files) {
      writeFileSync(join(cardDir, fname), rendered.get(fname) as string, "utf8");
      written.push(fname);
    }
    if (!backlog) {
      const artifactsDir = join(cardDir, "artifacts");
      mkdirSync(artifactsDir, { recursive: true });
      writeFileSync(join(artifactsDir, ".gitkeep"), "", "utf8");
      written.push("artifacts/.gitkeep");
    }
  } catch (error) {
    rmSync(cardDir, { recursive: true, force: true });
    throw error;
  }

  return written;
}

// ─── Trace ───────────────────────────────────────────────────────────────────

export type TraceEntryType = "finding" | "ruled-out" | "hypothesis" | "next-step";

export interface AppendTraceOptions {
  cardId: string;
  type: TraceEntryType;
  body: string;
  session?: string;
  date?: string;
}

export interface AppendTraceResult {
  path: string;
  linesBefore: number;
  linesAfter: number;
  bytesBefore: number;
  tokensAvoided: number;
  formatted: string;
}

const CHARS_PER_TOKEN = 4;

function lineCount(path: string): number {
  if (!existsSync(path)) {
    return 0;
  }
  const content = readFileSync(path, "utf8");
  if (content.length === 0) {
    return 0;
  }
  const lines = content.split("\n");
  if (content.endsWith("\n")) {
    lines.pop();
  }
  return lines.length;
}

/**
 * Append one structured entry to an active card's trace.md. Refuses if the
 * card exists but is not in `issues/active/` (naming the actual state), or
 * if the card cannot be found at all. Append-only: never reads and rewrites
 * the body — only `appendFileSync` touches an existing trace.md. If
 * trace.md doesn't exist yet (e.g. just activated from backlog), the
 * standard header is written first.
 */
export function appendTrace(opts: AppendTraceOptions, root: string = memoryRoot()): AppendTraceResult {
  const cardId = sanitizeCardId(opts.cardId);
  const body = opts.body.trim();
  if (!body) {
    throw new Error("appendTrace: empty entry body (body must not be empty or whitespace-only)");
  }

  const found = findCard(cardId, root);
  if (!found) {
    throw new Error(`appendTrace: no active card ${cardId} (looked in ${join(root, "issues", "active", cardId)})`);
  }
  if (found.state !== "active") {
    throw new Error(
      `appendTrace: ${cardId} is in issues/${found.state}/, not active. Traces are for active cards — activate it first (move it to issues/active/).`,
    );
  }

  const tracePath = join(found.dir, "trace.md");
  const session = opts.session ?? "opencode";
  const date = opts.date ?? nowMinuteIso();

  // Bootstrap the header if this card was activated from backlog with no
  // trace.md yet. This is the only write to trace.md that happens before the
  // append-only block below, and it only ever runs when the file is absent.
  if (!existsSync(tracePath)) {
    writeFileSync(tracePath, traceHeader(cardId), "utf8");
  }

  const linesBefore = lineCount(tracePath);
  const bytesBefore = statSync(tracePath).size;

  const block = `\n---\ndate: ${date}\nsession: ${session}\ntype: ${opts.type}\n---\n${body}\n`;
  appendFileSync(tracePath, block, "utf8"); // append-only: never rewrites prior entries

  const linesAfter = lineCount(tracePath);
  const tokensAvoided = Math.round(bytesBefore / CHARS_PER_TOKEN);

  const formatted =
    `Appended ${opts.type} entry to ${tracePath} (${linesBefore} -> ${linesAfter} lines)\n` +
    `  ~${tokensAvoided} tokens not pulled into context (appended without re-reading the trace)`;

  return { path: tracePath, linesBefore, linesAfter, bytesBefore, tokensAvoided, formatted };
}

// ─── Context assembly ────────────────────────────────────────────────────────

export type ContextMode = "compact" | "full";

export interface AssembleContextOptions {
  cardId: string;
  mode?: ContextMode;
  sections?: string[];
}

const SYSTEM_SECTION_ORDER: readonly string[] = SYSTEM_SUBDIRS;

function resolveSections(root: string, requested: string[] | undefined): string[] {
  if (requested && requested.length > 0) {
    return requested;
  }
  return SYSTEM_SECTION_ORDER.filter((name) => {
    const dir = join(root, "system", name);
    return existsSync(dir) && readdirSync(dir).some((f) => f.endsWith(".md"));
  });
}

function headingsOf(content: string): string[] {
  return content
    .split("\n")
    .filter((line) => /^##(?!#)\s*\S/.test(line))
    .map((line) => line.trim());
}

function buildSystemKnowledgeSection(root: string, sections: string[], mode: ContextMode): string {
  if (sections.length === 0) {
    return "_No system/ sections selected, or all selected sections are empty._";
  }

  const blocks: string[] = [];
  if (mode === "compact") {
    blocks.push("_Compact mode — showing headings only. Ask for full content on specific files if needed._");
  }

  for (const section of sections) {
    const dir = join(root, "system", section);
    const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".md")).sort() : [];
    if (files.length === 0) {
      blocks.push(`### ${section}/\n\n_(empty)_`);
      continue;
    }
    for (const file of files) {
      const content = readFileSync(join(dir, file), "utf8");
      if (mode === "full") {
        blocks.push(`### ${section}/${file}\n\n${content.trimEnd()}`);
      } else {
        const headings = headingsOf(content);
        blocks.push(`### ${section}/${file}\n\n${headings.length > 0 ? headings.join("\n") : "_(no headings)_"}`);
      }
    }
  }
  return blocks.join("\n\n");
}

/** Split a trace.md body into its leading header and its `---`-delimited entries. */
function splitTraceEntries(content: string): { header: string; entries: string[] } {
  const marker = /\n---\ndate:/g;
  const indices: number[] = [];
  let m: RegExpExecArray | null;
  while ((m = marker.exec(content)) !== null) {
    indices.push(m.index + 1); // +1 skips the leading \n, so the slice starts at "---"
  }
  if (indices.length === 0) {
    return { header: content, entries: [] };
  }
  const header = content.slice(0, indices[0]);
  const entries: string[] = [];
  for (let i = 0; i < indices.length; i++) {
    const start = indices[i];
    const end = i + 1 < indices.length ? indices[i + 1] : content.length;
    entries.push(content.slice(start, end));
  }
  return { header, entries };
}

function compactTrace(content: string): string {
  const { header, entries } = splitTraceEntries(content);
  if (entries.length === 0) {
    return content;
  }
  const total = entries.length;
  const last10 = entries.slice(-10);
  const note =
    total > 10 ? `_Showing last 10 of ${total} entries. Run in full mode to see all._\n\n` : "";
  return `${header.trimEnd()}\n\n${note}${last10.join("").trimEnd()}\n`;
}

function benchmarksHasEntries(content: string): boolean {
  const withoutComments = content.replace(/<!--[\s\S]*?-->/g, "");
  return /\ndate:\s*\S/.test(withoutComments) || /^date:\s*\S/m.test(withoutComments);
}

/**
 * Assemble a focused markdown context payload for priming a new AI analysis
 * session, pulling from the card (context.md/trace.md/benchmarks.md) and
 * selected `system/` sections.
 */
export function assembleContext(opts: AssembleContextOptions, root: string = memoryRoot()): string {
  const cardId = sanitizeCardId(opts.cardId);
  const mode: ContextMode = opts.mode ?? "compact";
  const found = findCard(cardId, root);
  if (!found) {
    throw new Error(`assembleContext: card not found: ${cardId}`);
  }

  const contextPath = join(found.dir, "context.md");
  const contextSection = existsSync(contextPath)
    ? readFileSync(contextPath, "utf8").trimEnd()
    : "_context.md not found for this card._";

  const tracePath = join(found.dir, "trace.md");
  let traceSection: string;
  if (!existsSync(tracePath)) {
    traceSection = "_trace.md not found for this card (local working state may not be present)._";
  } else {
    const traceContent = readFileSync(tracePath, "utf8");
    traceSection = (mode === "full" ? traceContent : compactTrace(traceContent)).trimEnd();
  }

  const benchmarksPath = join(found.dir, "benchmarks.md");
  const benchmarksContent = existsSync(benchmarksPath) ? readFileSync(benchmarksPath, "utf8") : "";
  const benchmarksSection = benchmarksHasEntries(benchmarksContent)
    ? benchmarksContent.trimEnd()
    : "_No promoted benchmarks logged on this card yet._";

  const sections = resolveSections(root, opts.sections);
  const knowledgeSection = buildSystemKnowledgeSection(root, sections, mode);

  return [
    `# RAG Context — ${cardId}`,
    `_Generated: ${nowMinuteIso()} | Mode: ${mode}_`,
    "",
    "## Active Card Summary",
    "",
    contextSection,
    "",
    "## Investigation History",
    "",
    traceSection,
    "",
    "## Relevant System Knowledge",
    "",
    knowledgeSection,
    "",
    "## Promoted Benchmarks on This Card",
    "",
    benchmarksSection,
    "",
  ].join("\n");
}

// ─── Promotion ───────────────────────────────────────────────────────────────

export interface PromoteFindingOptions {
  cardId: string;
  finding: string;
  impact?: string;
  /** Path relative to system/, e.g. 'known-behaviors/foo.md'. */
  targetPath: string;
  title?: string;
  sectionTitle?: string;
  session?: string;
  date?: string;
}

export interface PromoteFindingResult {
  systemPath: string;
  benchmarksPath: string;
  created: boolean;
}

function validateTargetPath(targetPath: string): string {
  const normalized = targetPath.replace(/\\/g, "/").replace(/^\/+/, "");
  const segments = normalized.split("/");
  if (!normalized || isAbsolute(targetPath) || segments.includes("..") || segments.includes(".")) {
    throw new Error(
      `promoteFinding: invalid targetPath (must be relative, stay under system/, no ".."): ${targetPath}`,
    );
  }
  return normalized;
}

function quoteFrontmatterValue(value: string): string {
  return /[:`]/.test(value) ? JSON.stringify(value) : value;
}

function renderSystemFrontmatter(f: {
  title: string;
  domain: string;
  sourceCards: string[];
  created: string;
  updated: string;
}): string {
  return [
    "---",
    `title: ${quoteFrontmatterValue(f.title)}`,
    `domain: ${f.domain}`,
    `source_cards: [${f.sourceCards.join(", ")}]`,
    `created: ${f.created}`,
    `updated: ${f.updated}`,
    "status: active",
    "format_gen: 3",
    "tags: []",
    "---",
    "",
  ].join("\n");
}

function extractBracketList(line: string): string[] {
  const m = line.match(/\[(.*)\]/);
  if (!m || !m[1].trim()) {
    return [];
  }
  return m[1]
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

/**
 * Update only `source_cards` (dedupe) and `updated` in an existing
 * system/ doc's frontmatter, leaving `format_gen` and every other line
 * untouched, then append a new `## section` at the end of the file.
 */
function appendSystemSection(
  content: string,
  opts: { sectionTitle: string; cardId: string; date: string; finding: string; impact?: string },
): string {
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n/);
  let updated = content;

  if (fmMatch) {
    const fmBody = fmMatch[1];
    const newLines = fmBody.split("\n").map((line) => {
      if (line.startsWith("source_cards:")) {
        const ids = extractBracketList(line);
        if (!ids.includes(opts.cardId)) {
          ids.push(opts.cardId);
        }
        return `source_cards: [${ids.join(", ")}]`;
      }
      if (line.startsWith("updated:")) {
        return `updated: ${opts.date}`;
      }
      return line;
    });
    const newFrontmatter = `---\n${newLines.join("\n")}\n---\n`;
    updated = newFrontmatter + content.slice(fmMatch[0].length);
  }

  const impactLine = opts.impact ? `**Impact**: ${opts.impact}\n` : "";
  const section = `\n## ${opts.sectionTitle}\n**Source**: ${opts.cardId} | ${opts.date}\n**Finding**: ${opts.finding}\n${impactLine}`;
  return `${updated.trimEnd()}\n${section}`;
}

/**
 * Promote a confirmed finding from a card to `system/`. Writes a new file
 * with frontmatter (or appends a new `## section` to an existing file,
 * updating only `source_cards`/`updated`), then records a `promoted` entry
 * in the card's benchmarks.md. Never touches trace.md.
 */
export function promoteFinding(opts: PromoteFindingOptions, root: string = memoryRoot()): PromoteFindingResult {
  const cardId = sanitizeCardId(opts.cardId);
  const found = findCard(cardId, root);
  if (!found) {
    throw new Error(`promoteFinding: card not found: ${cardId}`);
  }
  if (found.state === "backlog") {
    throw new Error(
      `promoteFinding: ${cardId} is in issues/backlog/; promote from an active (or done/archive) card`,
    );
  }

  const finding = opts.finding.trim();
  if (!finding) {
    throw new Error("promoteFinding: finding text must not be empty");
  }

  const relTarget = validateTargetPath(opts.targetPath);
  const systemPath = join(root, "system", ...relTarget.split("/"));
  const date = opts.date ?? todayIso();
  const session = opts.session ?? "opencode";
  const sectionTitle = opts.sectionTitle ?? opts.title ?? "Finding";

  const alreadyExists = existsSync(systemPath);
  if (!alreadyExists) {
    mkdirSync(dirname(systemPath), { recursive: true });
    const title = opts.title ?? sectionTitle;
    const domainSegments = relTarget.split("/").slice(0, -1);
    const domain = domainSegments.length > 0 ? domainSegments.join("/") : relTarget;
    const frontmatter = renderSystemFrontmatter({
      title,
      domain,
      sourceCards: [cardId],
      created: date,
      updated: date,
    });
    const impactLine = opts.impact ? `**Impact**: ${opts.impact}\n` : "";
    const body = `# ${title}\n\n## ${sectionTitle}\n**Source**: ${cardId} | ${date}\n**Finding**: ${finding}\n${impactLine}`;
    writeFileSync(systemPath, frontmatter + "\n" + body, "utf8");
  } else {
    const existingContent = readFileSync(systemPath, "utf8");
    const updatedContent = appendSystemSection(existingContent, {
      sectionTitle,
      cardId,
      date,
      finding,
      impact: opts.impact,
    });
    writeFileSync(systemPath, updatedContent, "utf8");
  }

  const benchmarksPath = join(found.dir, "benchmarks.md");
  const entry = `\n---\ndate: ${date}\nsession: ${session}\nfinding: ${finding}\ntarget: system/${relTarget}\nstatus: promoted\n---\n`;
  appendFileSync(benchmarksPath, entry, "utf8"); // never touches trace.md

  return { systemPath, benchmarksPath, created: !alreadyExists };
}
